name: gcaller
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1W

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  call_log: ^4.0.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7+1
  flutter_localizations:
    sdk: flutter
  flutter_overlay_window: ^0.4.4
  neopop: ^1.0.2
  permission_handler: ^11.0.1
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  cloud_firestore: ^4.16.0
  phone_number: ^2.1.0
  phone_state: ^1.0.4
  stacked: ^3.4.2
  oauth2_client: ^3.2.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Vector.png" 
 

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
